### ISSUE TITLE
How exclusion map are used ?

### ISSUE THREAD

**Issue by PhileasFrog** [mostafajahanifar/nuclick_torch#13]
Hi there,

Thanks for having share you great work. I've read your paper some weeks ago and explored your code. I don't understand where the exclusion map information is used in the training phase. It looks that in train.py you're just using the 'image' and 'mask' elements of the inputs not the 'others' as defined patch_extractor script. Could you clarify ?

Cheers

**Comment by mostafajahanifar** [comment]
Dear @PhileasFrog ,

Thanks for you interest in our repo.

If you look into `NuClickDataset` class, in particular the pre_processing function in L#82, you will see that we are concatenating the input image, inclusion and exclusion maps to generate network input which is returned in the output dictionary of `__getitem__` method with the key "image" (L#143).
 https://github.com/mostafajahanifar/nuclick_torch/blob/98d8439676f938b39cf906d16c0ec2fe23fde70a/data/dataset_generator.py#L82

Therefore, the array "image" in the `train.py` module does contain all image, inclusion and exclusion maps information. However, it might be better to rename this variable to "input" in the future to avoid confusion and improve user readability.

Thanks for raising this issue. I think this answers your question, please feel free to close the issue.

**Comment by PhileasFrog** [comment]
Great thanks for the answer !
