### ISSUE TITLE
hello, is there any experiment with glands

### ISSUE THREAD

**Issue by supercarry666** [mostafajahanifar/nuclick_torch#14]

**Comment by mostafajahanifar** [comment]
Hi @supercarry666 ,

Thanks for your interest in our work. We decided not to include gland segmentation in this work for now as it requires some special considering. We, however, plan to release the implementation of a more generalized version of that algorithm (which can handle whole slide images) in the future in [TIAToolbox](https://github.com/TissueImageAnalytics/tiatoolbox).
If you are only interested in the results we get on Gland segmentation, you should be able to find those experiments in our paper:

https://arxiv.org/abs/2005.14511
